### ISSUE TITLE
Merge / move to new okfn/a

### ISSUE THREAD

**Issue by rufuspollock** [okfn/branding#1]
Based on convo with @pwalsh, now we have https://github.com/okfn/a we should merge to 

https://github.com/okfn/a/tree/master/a/img/oki

EPS should probably go to drive and be linked from a README rather than stored to keep things relatively lightweight.

**Comment by pwalsh** [comment]
WONTFIX. We are using this for heavy branding assets, and `a.okfn.org` for web assets.
